[mongo]
connection_string = "mongodb+srv://sharavanak20:8TBG9CB8Dak9hRRr@cluster0.k1dnshz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
port = 27017
username = "sharavanak20"
password = "8TBG9CB8Dak9hRRr"